### ISSUE TITLE
negative or zero item sizes are not supported in the flow layout

### ISSUE THREAD

**Issue by Sweeper777** [gkye/MaterialColorPicker#1]
I am using `MaterialColorPicker` like this:

```
@IBOutlet var placeholderView: UIView!

override func viewDidLoad() {
    super.viewDidLoad()
    self.preferredContentSize = CGSize(width: 400, height: 200)

    let colorPicker = MaterialColorPicker()
    colorPicker.frame = placeholderView.frame
    colorPicker.addConstraints(placeholderView.constraints)
    colorPicker.delegate = self
    colorPicker.dataSource = self
    let contentView = tableView.cellForRowAtIndexPath(NSIndexPath(forRow: 0, inSection: 0))?.contentView
    contentView?.addSubview(colorPicker)
    placeholderView.removeFromSuperview()
}

func colors() -> [UIColor] {
    return ["ff0000", "00ff00", "0000ff", "ff00ff", "ffff00", "00ffff"].map { UIColor(hexString: $0)! }
}

func didSelectColorAtIndex(index: Int, color: UIColor) {

}
```

The reason that I have a `placeholderView` is because I am too lazy to add constraints to it in code. Anyway, when I run the app, this message pops up and the color picker shows nothing:

> negative or zero item sizes are not supported in the flow layout

Bug?

**Comment by gkye** [comment]
Could you provide an example project which replicates this issue?

**Comment by Sweeper777** [comment]
After finding it not working, I switched to another library, so, sorry I can't provide one. But here is what I did:
- Create a table view controller
- add a static cell to it containing a `UIView` which is an Outlet connected to `placeholderView` as you can see in the code I provided above.
- then you just add the code above in the table view controller file.

Can you reproduce?

**Comment by gkye** [comment]
That's okay and I'm quite sure `let colorPicker = MaterialColorPicker()` is the issue. The picker is not being initialized correctly. Try

``` swift
    let colorPicker = MaterialColorPicker(frame: placeholder.frame)
```

Also I will be adding storyboard support soon to avoid manually creating constraints

**Comment by Sweeper777** [comment]
Thanks! Please tell me when you update it!

**Comment by gkye** [comment]
Storyboard support has been now added :+1:
